### ISSUE TITLE
All Images are aligned on left side in design 3

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1031]
All Images are aligned on left side even though we set the images on right side and center in design 3

Ref: https://secure.helpscout.net/conversation/408586748/14867/?folderId=1060551

**Comment by ahmedkaludi** [comment]
Fixed

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1040

Still persist, have to check it properly

**Comment by ahmedkaludi** [comment]
Fixed in 0.9.59
