### ISSUE TITLE
Fonts not loading via AMP CDN, Why so?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1735]
But with last updates I have this problem.
What can I do?
The problem is only when you visit amp in Google (ex. https://www.stintup.com/flixbus-promoter-opinioni/amp/ is not showing problem but https://www.google.it/amp/s/www.stintup.com/flixbus-promoter-opinioni/amp/ yes).

https://imgur.com/tnuukW1

**Comment by MohammedKaludi** [comment]
Looks like there is some issue is with AMP Cache, Waiting for the reply from AMP team.

**Comment by githubjabbar** [comment]
This is not the actual issue of AMP cache, we need to find the solution to this issue.

**Comment by sanderdewaal** [comment]
I still have this issue. Is it solved already in an update?

**Comment by MARQAS** [comment]
@sanderdewaal Can you please contact us on team@magazine3.com ? So we will check and help you fix this ASAP.

**Comment by MARQAS** [comment]
duplicate ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2144

**Comment by Zabi09** [comment]
@sanderdewaal We have already sent you a message from team@magazine3.com a few days back please check it and let us know.

**Comment by Zabi09** [comment]
One user was also facing the same issue - https://secure.helpscout.net/conversation/579901517/26110?folderId=1914712 and we have debugged his issue and told him to contact the hosting provider to check the CORS Policy and his issue was fixed But now we don't have any user who has this issue so moving this ticket to waiting.....

And if someone reading this message and have this issue then feel free to create a new ticket and we will definitely fix it for you.

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/671946891/35437/

**Comment by ahmedkaludi** [comment]
We still don't know the root cause of this issue, most of the issues were resolved by changing CORS policy on the user's end. 

This issue is not occurring from our end.

**Comment by sadesarrollo** [comment]
I have the same issue here.
