### ISSUE TITLE
Wrong url in Non-Amp Version link on blog posts page and category archives

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2424]
It seems that the link (Non-amp version) back to the canonical page for a category page or blog posts page - pages 2,3 etc is broken. It doesn't return to the canonical which is rendered correctly in the meta area.  The link only works correctly for the first page on an archive. I have only tested design 2.

**Comment by Zabi09** [comment]
@Frenchomatic 
We have updated the code will you please update that on your end and let us know

**Comment by Frenchomatic** [comment]
Downloaded you commit. This seems to now work correctly and it also solves the non-AMP version link part of this #2425 . A minor thing but you still have an unwanted or needed space in the TOP link `<a href="#header">TopSPACEHERE</a>`

**Comment by Frenchomatic** [comment]
Yerr the specific edit works in the existing features.php but the whole file crashes my version 0.9.97.9 - I can see in the commit a few things have changed.

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
