### ISSUE TITLE
Need to create an ID Support on the page builder

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2474]
Ref:  https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/chats/2af9afc5-6132-4707-84f3-d0156c7078c6

Screenshot: https://monosnap.com/direct/vQ1aTZRGZTB17O5sB1ZIzy3vBvxh5u
https://monosnap.com/direct/KK4UI127nOpl5LC3ZyWcNVHV8FbZxd

**Comment by patrickbloemer** [comment]
Good Morning,
I up to date to plugin to version 0.9.97.12 and the ID's insertion is still not Working

![image](https://user-images.githubusercontent.com/32529480/44727982-afca3c80-aab1-11e8-9246-146eb016846c.png)

![image](https://user-images.githubusercontent.com/32529480/44728007-c4a6d000-aab1-11e8-9369-6ce2abe59d42.png)

**Comment by MohammedKaludi** [comment]
@patrickbloemer thank you for reporting, also classes need spacing in Row Classes. 

@Zabi09 Please check it in the morning.

**Comment by MohammedKaludi** [comment]
classes are messing up

**Comment by patrickbloemer** [comment]
Has the ID problem been resolved?

**Comment by Zabi09** [comment]
@patrickbloemer Sorry for the inconvenience and yes the issue is fixed in this ticket - #2515

**Comment by MohammedKaludi** [comment]
@Zabi09 have you added the class and tested it by your self?

If yes, then why I'm seeing the same issue mentioned two times and still not fixed?

http://take.ms/IZlED ??

Fix this ASAP on Monday Morning.

**Comment by Zabi09** [comment]
@Zabi09 have you added the class and tested it by your self?
No, I have just added the ID option and checked that option only before and now I have also properly added the class as well on this ticket - #2515

**Comment by Zabi09** [comment]
Here I forgot to close the "ifend_row_id" so because of that the classes where messing up and I have fixed it in #2515

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
