### ISSUE TITLE
Debug warnings after 0.9.97.15

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2532]
Debug warnings after 0.9.97.15

![screenshot_20180914-133521](https://user-images.githubusercontent.com/16618009/45558594-ed72e780-b85d-11e8-902e-f71ac05e339e.png)

**Comment by MohammedKaludi** [comment]
`if($redux_builder_amp['ampforwp-bread-crumb-type'] == 'tags'){` code is present in D1,D2 and D3 is still present.

Need to update that code as well.

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by MARQAS** [comment]
Already resolved in master, can be closed

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
accelerated-mobile-pages\components\breadcrumb\breadcrumb.php 

Still missing in components

**Comment by Zabi09** [comment]
Need to add the above commits in master because it is present in beta but not in the master

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
pushed in 0.9.97.44
