### ISSUE TITLE
If Jetpack Sharing Button is active it comes in APM page and cause validation error

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#26]
If Jetpack is installed, and Sharing buttons are active, as by default it serves at the bottom of the content.

From the amp theme function or in the single we could use this method to remove jetpack sharing filter. Look [here](https://jetpack.com/2013/08/15/remove-sharing-buttons-mobile-theme/)

> remove_filter( 'the_content', 'sharing_display', 19 );

**Comment by Asif2BD** [comment]
@MohammedKaludi Not working. Here it's still like before - http://d.pr/i/MBLc

**Comment by ahmedkaludi** [comment]
@Asif2BD Can you post the website URL?

**Comment by Asif2BD** [comment]
@ahmedkaludi Yes. One example page - https://asif.im/2862/wordpress-4-6-pepper-released/?amp

**Comment by ahmedkaludi** [comment]
@Asif2BD Thanks! We will look into this and take action immediately. 

@MohammedKaludi We need to debug and fix this issue in the next update ASAP

Regards,
Ahmed

**Comment by MohammedKaludi** [comment]
@Asif2BD  and @ahmedkaludi I will check the issue tonight.

**Comment by MohammedKaludi** [comment]
@Asif2BD Issue was fixed, as I have tested it once again on the live server.

With Jetpack Sharing and Related posts active:
Regular page : http://magazine3.com/garage/5-things-i-love-about-manila/
AMP page      : http://magazine3.com/garage/5-things-i-love-about-manila/?amp

and also it is working on your site https://asif.im/2862/wordpress-4-6-pepper-released/?amp

I'm closing this ticket.

**Comment by Asif2BD** [comment]
Thanks @MohammedKaludi . Though the "Related Post" this text still appears.

**Comment by MohammedKaludi** [comment]
@Asif2BD Yes, I have fixed that in my local server, and will be removed in the next update push, which is not far away.
