### ISSUE TITLE
Serious issue  - HTML not being rendered on cookie consent notifications

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2671]
Any html being entered into the admin panel for 404 error pages or for cookies consent notifications is not rendering as html but as plain text. It is just displaying the code as it is entered. For example, putting this into the notifications box doesn't get rendered properly

`Ce site utilise des cookies et est en conformité avec le RGPD - <a href="https://www.mydomain.com/legal-info/">more information</a>`

It means sites are now illegal in the EU as people can't click through to the cookies/GPDR page. Without an immediate fix , the plugin will have to be removed from all of my EU based web sites - so 5 of them.

**Comment by Frenchomatic** [comment]
Need a fix within a few days or I will have to remove the plugin for my EU based sites.

**Comment by Zabi09** [comment]
This code is committed to 0.9.97.20-beta and not in 98 because the nicholasgriffintn for Cookie Notification Code is not available in that.

**Comment by Frenchomatic** [comment]
In the 404.php file for design 2 you are enclosing everything within   `<h1 class="amp-wp-title">`.  This means all text entered into the admin box for 404 pages is very large. Take the h1 out or people can't really produce a reasonably nice 404 page which uses html.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 0.9.97.21

**Comment by Frenchomatic** [comment]
This is not completely fixed for the 404 page because a `<h1 class="amptitle">` tag is being placed around all of the content. It means html within your 404 error page doesn't show as expected. The H1 needs to be removed (see above).
