### ISSUE TITLE
Featured image and link shared on twitter issues

### ISSUE THREAD

**Issue by venchy10** [ahmedkaludi/accelerated-mobile-pages#3075]
Hi,
1. For some reasons, all my featured images and some of the images within the post don't show up at all in my AMP
2. When I share a post on Twitter, the link doesn't take you to the actual post when you click on it, instead, it takes you to the Homepage. 
I really hope you can provide a fix for these issues.

**Comment by MARQAS** [comment]
Hi @venchy10, Can you please share the URL? and screenshots?

**Comment by venchy10** [comment]
Hi,
I realize your plugin doesn't play nice with lazyload. I deactivate lazyload and all the images appear in AMP. I use Smush plugin by the way, is there any way you can make it compatible with your plugin.
Twitter, Linkedin, etc when I share a post on those platforms it doesn't take me to the actual URL. If you go on my Twitter page: @gotechtor, click on any post that was recently shared, you'll see what I mean. It will take you to the homepage, in some case it will take you to the non-AMP version, which is weird.
Thanks for your help.

**Comment by MARQAS** [comment]
Regarding the Smush plugin, We have already resolved it here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2990

And regarding the social sharing, Is it happening only when Smush plugin is activated or all the time?

**Comment by venchy10** [comment]
No, unfortunately, it's not resolved. The featured images are still missing even with the last update. I can confirm all the images within the post appear now, but not the featured image. There's a big blank space in the sport where the featured is supposed to appear.

Regarding social sharing, it's happening with Smuch plugin activated.

Thanks.

**Comment by Zabi09** [comment]
We have fixed the issue of featured images with Smuch plugin and we have committed on this ticket -  https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2990

**Comment by MohammedKaludi** [comment]
@venchy10 can you please confirm that images are still not coming when shared on social media with Smuch plugin activated?

**Comment by MohammedKaludi** [comment]
Moving to ready pipe for now.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
