### ISSUE TITLE
Warning at the top of the site : array_merge(): Expected parameter 1 to be an array, bool given in /homepages/43/d473991142/htdocs/clickandbuilds/WordPress/Alteszollhaus/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 224

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3434]
ref:https://secure.helpscout.net/conversation/900827906/73462?folderId=3004564
screenshot: https://monosnap.com/file/oVSXqRpqRWVllaudz6PWOZe6BU0JLl

**Comment by MohammedKaludi** [comment]
fixed in this commit:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/96ae3cf00f391861e3f959d10205b0d940f40894#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R212

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64

**Comment by jammayer** [comment]
updated plugin with the new patch but it didn't fix it. It was replaced by this. 
Warning: array_merge(): Argument #1 is not an array in /home/socia715/conversologie.com/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 225

This can be seen on WP Login page and inside admin dashboard. 

<img width="1159" alt="arrayampwp" src="https://user-images.githubusercontent.com/52858901/61260198-6110b880-a7d1-11e9-8166-b6fc82b758b8.png">

**Comment by MohammedKaludi** [comment]
This is strange, I apologize for the inconvenience. I'll check as soon as I reach to the office.

**Comment by MohammedKaludi** [comment]
👍

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.65

**Comment by MohammedKaludi** [comment]
> updated plugin with the new patch but it didn't fix it. It was replaced by this.
> Warning: array_merge(): Argument #1 is not an array in /home/socia715/conversologie.com/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 225
> 
> This can be seen on WP Login page and inside admin dashboard.
> 
> <img alt="arrayampwp" width="1159" src="https://user-images.githubusercontent.com/52858901/61260198-6110b880-a7d1-11e9-8166-b6fc82b758b8.png">

Can you please check after the latest update if the issue is fixed or not.

**Comment by jammayer** [comment]
This has been fixed. Thanks so much!
