### ISSUE TITLE
Need to make compatibility with "Transposh WordPress Translation" plugin

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3895]
We need to make compatibility with the "Transposh WordPress Translation" plugin. 
https://wordpress.org/plugins/transposh-translation-filter-for-wordpress/

Ref: https://secure.helpscout.net/conversation/1018035819/99900?folderId=3257665

**Comment by udiudiudiudi** [comment]
there are 2 issues with transpoch.
1. the only option that is working with transpoch and ampforwp for translation is the flags, the other options don't work well with ampforwp
2. when you click on arabic flag translation, the menu is all over the screen, but with left to english languagues the menu is normal

**Comment by udiudiudiudi** [comment]
wasim, indeed its better now, but still when you click the menu its all over the screen
if you however click on the opposite side of the wording timezone, it does close the menue, but an X is not showing

**Comment by udiudiudiudi** [comment]
it is still not working: look at link: https://www.linkedin.com/feed/update/urn:li:activity:6611191591405182976

**Comment by udiudiudiudi** [comment]
any update on this please, all the people who go to mobile to this link, are seeing window all over their screen: [https://www.saveatrain.com/blog/london-paris-train/?lang=he](https://www.saveatrain.com/blog/london-paris-train/?lang=he) or =ar

**Comment by WasimM3** [comment]
@udiudiudiudi - Last time we fixed the issue in your end and our side as well, but we didn't push the ticket to live but you updated your AMPFORWP version so you lost the fix. Again we fixed at your side. Please don't update the plugin until this ticket is pushed to live.

**Comment by udiudiudiudi** [comment]
i just checked: https://www.saveatrain.com/blog/milan-rome-train/amp/?lang=he
on safari and chrome and it is still not working

https://ibb.co/DbDSStz
https://ibb.co/wQTv99t

**Comment by MohammedKaludi** [comment]
Escape the $_GET['lang'] before using it.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ca98e2be0972bf4cd8fc0cea44bea2f3e5710033#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7831

also add `function_exists` on the hook.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ca98e2be0972bf4cd8fc0cea44bea2f3e5710033#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7829

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6

**Comment by udiudiudiudi** [comment]
not sure what has happened, but maybe its related to transpoch releasing a new version on the 1/1/2020

the amp if you surf from chrome mobile or safari mobile, again shows the menu on the screen
[https://www.saveatrain.com/blog/famous-film-spots-europe/amp/?lang=he](https://www.saveatrain.com/blog/famous-film-spots-europe/amp/?lang=he)

**Comment by WasimM3** [comment]
Hi @udiudiudiudi,
I have just checked this URL 
https://www.saveatrain.com/blog/famous-film-spots-europe/amp/?lang=he
and it's working fine for me can you please check it once and let us know.

**Comment by udiudiudiudi** [comment]
i check on sarafi on my iphone, some links are ok and some links are not ok
when i check on chrome emulator, it works, so i think you should check on chrome and safari on mobile, just to make sure 
maybe on my end i have some cache, but if you ask me, its still not solved, since i also checked old blogs for =he and =ar

**Comment by udiudiudiudi** [comment]
wasimm3, did you manage to check directly from mobile [](https://www.saveatrain.com/blog/) and then looking at arabic and hebrew?

**Comment by akashagrjsr** [comment]
The issue is still occurring at our end on the emulator and we will fix it.

**Comment by udiudiudiudi** [comment]
i confirmed to your suggest that arabic and hebrew are now working fine, and tested these links
[https://www.saveatrain.com/blog/london-paris-train/amp/?lang=he](https://www.saveatrain.com/blog/london-paris-train/amp/?lang=he)

and
[https://www.saveatrain.com/blog/best-attractions-kids-europe/?lang=ar](https://www.saveatrain.com/blog/best-attractions-kids-europe/?lang=ar)

**Comment by MohammedKaludi** [comment]
@udiudiudiudi Thank you for testing and letting us know.

We are also testing the issue at our end, once the testing is done we will push the update.

Hopefully in tomorrow's update we will push this ticket.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
