### ISSUE TITLE
Issue still persists after the latest update with yoast

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4434]
Two people reported the issue and need to make sure AMPforWP and yoast works in all scenarios.

**Comment by MohammedKaludi** [comment]
@Zabi09 do look into this issue first thing in the morning.

**Comment by djixas** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4430

Still not fixed, my amp pages are invalid for a week now

**Comment by Zabi09** [comment]
@djixas Can you please send us your website URL where your AMP pages are showing invalid I will check once and will fix it as soon as I can.

**Comment by Doc2b191** [comment]
> @djixas Can you please send us your website URL where your AMP pages are showing invalid I will check once and will fix it as soon as I can.

Hi @Zabi09, I'm experiencing this issue as well. Where should I sent my website url to?

Thanks!

**Comment by djixas** [comment]
> @djixas Can you please send us your website URL where your AMP pages are showing invalid I will check once and will fix it as soon as I can.

https://www.airyhair.com/blog/amp/

**Comment by Zabi09** [comment]
@djixas When I try to open the URL it is not working - https://monosnap.com/file/CYQ84noGNVZMy0FLP8Z7wPdWwlGdld

Will you please check once and let us know

**Comment by Zabi09** [comment]
@Doc2b191 Are you using the latest version of our AMP plugin that is 1.0.47 and still having the issue? You can send us your website url here only so that we can check once and let you know

**Comment by djixas** [comment]
Latest, correct, this is weird! Does proxy load site for you? I can see live visitors and no issues on my end

**Comment by Doc2b191** [comment]
> @Doc2b191 Are you using the latest version of our AMP plugin that is 1.0.47 and still having the issue? You can send us your website URL here only and if you don't want to share your website in public then you can also send us privately by sending us on https://ampforwp.com/support/ so that we can check once and let you know

Hi @Zabi09,

As of this morning, it looks like the errors in search console are going down. For now, it seems like the issue has been resolved.

Thank you!

**Comment by djixas** [comment]
The issue is NOT resolved because errors are down but HOME PAGE still gives error

**Comment by Doc2b191** [comment]
> The issue is NOT resolved because errors are down but HOME PAGE still gives error

Sorry about that. I should have clarified that the issue has been resolved **for me**.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update

**Comment by djixas** [comment]
Still not solved

https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=nmec1sJEyNQUbMfs0Uy4fw
